### ISSUE TITLE
There is no example in repo

### ISSUE THREAD

**Issue by folkien** [wojtke/music-video-automaker#2]
Missing example video/audio from example command line 

```shell
python merge_testing.py "src/penguins.mp4" "src/wolves.mp3" -o "out/merged.mp4" --threshold 2
```

**Comment by adam-kwiatkowski** [comment]
This example only illustrates how to populate the command placeholders with something meaningful. Uploading example input files would unnecessarily increase the repo size. You can find a set of public test videos here https://gist.github.com/jsturgis/3b19447b304616f18657 and sample audio files here https://github.com/rafaelreis-hotmart/Audio-Sample-files
